# Copyright Intel (c) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Check if Kata Containers runtime classes exist for `K3s`
  shell: |
    KUBECONFIG=/etc/rancher/k3s/k3s.yaml kubectl get runtimeclass | grep kata-clh &&
    KUBECONFIG=/etc/rancher/k3s/k3s.yaml kubectl get runtimeclass | grep kata-qemu
  register: get_runtime_class
  ignore_errors: yes
  tags: install
