# Copyright Intel (c) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Check CRI notation used by containerd
  lineinfile:
    path: "{{ containerd_conf }}"
    line: "version = 2"
    state: present
  check_mode: yes
  register: version_2
  tags: install

- set_fact:
    containerd_cri_notation: "cri"
  when: version_2 is changed
  tags: install

- set_fact:
    containerd_cri_notation: "\"io.containerd.grpc.v1.cri\""
  when: version_2 is not changed
  tags: install

- name: Configure containerd for Kata Containers
  blockinfile:
    path: "{{ containerd_conf }}"
    backup: yes
    marker_begin: "BEGIN -- ANSIBLE MANAGED BLOCK -- {{ item }} configuration"
    marker_end: "END -- ANSIBLE MANAGED BLOCK -- {{ item }} configuration"
    block: |
      [plugins.{{ containerd_cri_notation }}.containerd.runtimes.kata-{{ item }}]
        runtime_type = "io.containerd.kata-{{ item}}.v2"
        privileged_without_host_devices = true
        pod_annotations = ["io.katacontainers.*"]
        [plugins.{{ containerd_cri_notation }}.containerd.runtimes.kata-{{ item }}.options]
          ConfigPath = "/opt/kata/share/defaults/kata-containers/configuration-{{ item }}.toml"
  diff: true
  register: containerd_conf_diff
  with_items:
    - clh
    - qemu
  tags: install
