# Copyright Intel (c) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Create containerd tmpl file for `K3s`
  file:
    src: "{{ containerd_conf }}"
    dest: "{{ containerd_conf }}.tmpl"
    state: hard

- name: Set the containerd tmpl file as containerd_conf
  set_fact:
    containerd_conf: "{{ containerd_conf }}.tmpl"

- name: Configure containerd for Kata Containers
  include_tasks:
    configure_containerd_default.yml

- name: Restart `K3s` service
  service:
    name: k3s
    state: restarted
