# Copyright Intel (c) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
---
- hosts: all
  become: yes
  tasks:
    - name: Create kataRuntimeClasses.yaml file
      copy:
        dest: /tmp/kataRuntimeClasses.yaml
        content: |
          ---
          kind: RuntimeClass
          apiVersion: node.k8s.io/v1
          metadata:
              name: kata-qemu
          handler: kata-qemu
          overhead:
              podFixed:
                  memory: "160Mi"
                  cpu: "250m"
          ---
          kind: RuntimeClass
          apiVersion: node.k8s.io/v1
          metadata:
              name: kata-clh
          handler: kata-clh
          overhead:
              podFixed:
                  memory: "130Mi"
                  cpu: "250m"
      tags: install

    - name: Apply kataRuntimeClasses.yaml
      include_tasks:
        apply_runtime_classes_{{ k8s_deployment }}.yml
      tags: install
