# Copyright Intel (c) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
---
- hosts: all
  tasks:
    - name: Check if Kata Containers runtime classes exist
      delegate_to: localhost
      shell: |
        kubectl get runtimeclass | grep kata-clh &&
        kubectl get runtimeclass | grep kata-qemu
      register: get_runtime_class
      ignore_errors: yes

    - name: Create kataRuntimeClasses.yaml file
      delegate_to: localhost
      copy:
        dest: /tmp/kataRuntimeClasses.yaml
        content: |
          ---
          kind: RuntimeClass
          apiVersion: node.k8s.io/v1
          metadata:
              name: kata-qemu
          handler: kata-qemu
          overhead:
              podFixed:
                  memory: "160Mi"
                  cpu: "250m"
          ---
          kind: RuntimeClass
          apiVersion: node.k8s.io/v1
          metadata:
              name: kata-clh
          handler: kata-clh
          overhead:
              podFixed:
                  memory: "130Mi"
                  cpu: "250m"
      when: get_runtime_class.rc != 0

    - name: Apply kataRuntimeClasses.yaml
      delegate_to: localhost
      shell: |
        kubectl apply -f /tmp/kataRuntimeClasses.yaml
      when: get_runtime_class.rc != 0

    - name: Remove kataRuntimeClasses.yaml
      delegate_to: localhost
      file:
        path: /tmp/kataRuntimeClasses.yaml
        state: absent
