# Copyright Intel (c) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Create containerd tmpl file for `RKE2`
  file:
    src: "{{ containerd_conf }}"
    dest: "{{ containerd_conf }}.tmpl"
    state: hard

- name: Set the containerd tmpl file as containerd_conf
  set_fact:
    containerd_conf: "{{ containerd_conf }}.tmpl"

- name: Configure containerd for Kata Containers
  include_tasks:
    configure_containerd_default.yml

- name: Get service state informationas fact data
  service_facts:

- name: Restart `RKE2` server service
  service:
    name: rke2-server
    state: restarted
  when: ansible_facts.services['rke2-server.service']['state'] == 'running'

- name: Restart `RKE2` agent service
  service:
    name: rke2-agent
    state: restarted
  when: ansible_facts.services['rke2-agent.service']['state'] == 'running'
