# Copyright Intel (c) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Check whether there's already a /etc/containerd directory created
  stat:
    path: /etc/containerd
  register: containerd_dir
  tags: install

- name: Create /etc/containerd
  file:
    path: /etc/containerd
    state: directory
  when: containerd_dir.stat.exists
  tags: install

- name: Check whether there's already a {{ containerd_conf }} created
  stat:
    path: "{{ containerd_conf }}"
  register: containerd_conf_file
  tags: install

- name: Create containerd configuration
  shell: |
    containerd config default > {{ containerd_conf }}
  when: not containerd_conf_file.stat.exists
  tags: install

- name: Configure containerd for Kata Containers
  include_tasks:
    configure_containerd_default.yml
  tags: install

- name: Restart `containerd` service
  service:
    name: containerd
    state: restarted
  when: containerd_conf_diff.changed
  tags: install

- name: Wait for node to be ready after service restart
  shell: |
     $([[ $(KUBECONFIG=/etc/kubernetes/admin.conf kubectl get node $(cat /etc/hostname) -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}') == "True" ]])
  args:
    executable: /bin/bash
  register: kubelet_ready
  until: kubelet_ready.rc == 0
  retries: 60
  delay: 5
  when: containerd_conf_diff.changed
  tags: install
