# Copyright Intel (c) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Create containerd tmpl file for `RKE2`
  file:
    src: "{{ containerd_conf }}"
    dest: "{{ containerd_conf }}.tmpl"
    state: hard
  tags: install

- name: Set the containerd tmpl file as containerd_conf
  set_fact:
    containerd_conf: "{{ containerd_conf }}.tmpl"
  tags: install

- name: Configure containerd for Kata Containers
  include_tasks:
    configure_containerd_default.yml
  tags: install

- name: Get service state informationas fact data
  service_facts:
  tags: install

- name: Restart `RKE2` server service
  service:
    name: rke2-server
    state: restarted
  when: ansible_facts.services['rke2-server.service']['state'] == 'running'
  tags: install

- name: Restart `RKE2` agent service
  service:
    name: rke2-agent
    state: restarted
  when: ansible_facts.services['rke2-agent.service']['state'] == 'running'
  tags: install

- name: Wait for node to be ready after service restart
  shell: |
     $([[ $(KUBECONFIG=/etc/rancher/rke2/rke2.yaml PATH=$PATH:/var/lib/rancher/rke2/bin/ kubectl get node $(cat /etc/hostname) -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}') == "True" ]])
  args:
    executable: /bin/bash
  register: kubelet_ready
  until: kubelet_ready.rc == 0
  retries: 60
  delay: 5
  tags: install
