# Copyright Intel (c) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Check whether there's already a {{ containerd_conf }}.tmpl created
  stat:
    path: "{{ containerd_conf }}.tmpl"
  register: containerd_conf_file
  tags: install

- name: Create containerd tmpl file for `K3s`
  file:
    src: "{{ containerd_conf }}"
    dest: "{{ containerd_conf }}.tmpl"
    state: hard
  when: not containerd_conf_file.stat.exists
  tags: install

- name: Set the containerd tmpl file as containerd_conf
  set_fact:
    containerd_conf: "{{ containerd_conf }}.tmpl"
  tags: install

- name: Configure containerd for Kata Containers
  include_tasks:
    configure_containerd_default.yml
  tags: install

- name: Restart `K3s` agent service
  service:
    name: k3s-agent
    state: restarted
  when: containerd_conf_diff.changed
  tags: install
