# Copyright Intel (c) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
---
#- name: Check whether there's already a {{ containerd_conf }} created
#  stat:
#    path: "{{ containerd_conf }}"
#  register: containerd_conf_file
#  tags: install

- name: Create containerd configuration
  shell: |
    /var/lib/k0s/bin/containerd config default > {{ containerd_conf }}
#  when: not containerd_conf_file.stat.exists
  tags: install

- name: Ensure containerd configuration's root points to `K0s`
  replace:
    path: "{{ containerd_conf }}"
    regexp: "root = \"/var/lib/containerd\""
    replace: "root = \"/var/lib/k0s/containerd\""
  tags: install

- name: Ensure containerd configuration's state points to `K0s`
  replace:
    path: "{{ containerd_conf }}"
    regexp: "state = \"/run/containerd\""
    replace: "state = \"/var/lib/k0s/run/containerd\""
  tags: install

- name: Ensure containerd configuration points to the `K0s` socket
  replace:
    path: "{{ containerd_conf }}"
    regexp: "address = \"/run/containerd/containerd.sock\""
    replace: "address = \"/var/lib/k0s/run/containerd.sock\""
  tags: install

- name: Configure containerd for Kata Containers
  include_tasks:
    configure_containerd_default.yml
  tags: install

- name: Restart `k0s`
  shell: |
    k0s stop && k0s start
  when: containerd_conf_diff.changed
  tags: install
