# Copyright Intel (c) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Check whether there's already a /etc/containerd directory created
  stat:
    path: /etc/containerd
  register: containerd_dir
  tags: install

- name: Create /etc/containerd
  file:
    path: /etc/containerd
    state: directory
  when: containerd_dir.stat.exists
  tags: install

- name: Check whether there's already a {{ containerd_conf }} created
  stat:
    path: "{{ containerd_conf }}"
  register: containerd_conf_file
  tags: install

- name: Create containerd configuration
  shell: |
    containerd config default > {{ containerd_conf }}
  when: not containerd_conf_file.stat.exists
  tags: install

- name: Configure containerd for Kata Containers
  include_tasks:
    configure_containerd_default.yml
  tags: install

- name: Restart `containerd` service
  service:
    name: containerd
    state: restarted
  when: containerd_conf_diff.changed
  tags: install
